version: '3'

services:
  www:
    build: ./front
    volumes:
     - "./front/static:/static"
  api:
    build: ./api
  websocket:
    build: ./websocket
networks:
  default:
    external:
      name: demo-network
