version: '3'

services:
  reverse-proxy:
    image: traefik:1.6.4 # The official Traefik docker image
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The API port
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
networks:
    default:
        external:
            name: demo-network
