version: '3'

services:
  reverse-proxy:
    image: traefik:1.6.4 # The official Traefik docker image
    ports:
      - "80:80"     # The HTTP port
      - "5002:80"     # The HTTP port
      - "443:443"   # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./access.log:/tmp/access.log
networks:
  default:
    external:
      name: demo-network
