apiVersion: v1

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: example
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: cubestore-api
        ports:
        - name: http
          containerPort: 80
---

 kind: Service
metadata:
  name: cubestore-api
spec:
  ports:
  - name: http
    port: 80
---

kind: Ingress
metadata:
  name: example
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  rules:
  - host: www.cubestore.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: cubestore-api
          servicePort: http