version: '3'

services:
  reverse-proxy:
    image: traefik:1.6.4 # The official Traefik docker image
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./access.log:/tmp/access.log

  www:
   build: ./front
   volumes:
    - "./front/static:/static"
   labels:
       - "traefik.frontend.rule=Host:better.demo"
#       - traefik.frontend.auth.basic=user:$$apr1$$9Cv/OMGj$$ZomWQzuQbL.3TRCS81A1g/

  api:
    build: ./api
    labels:
       - "traefik.frontend.rule=Host:better.demo;PathPrefix:/api"
#      - traefik.backend.loadbalancer.stickiness=true
networks:
  default:
    external:
      name: demo-network
