version: '3'

services:
  www:
   build: ./front
   labels:
    - "traefik.frontend.rule=Host:www.cubestore.com"

  api:
   build: ./api
   labels:
    - "traefik.frontend.rule=Host:www.cubestore.com;PathPrefix:/api"

networks:
  default:
    external:
      name: demo-network
