version: '3'

services:
  www:
   build: ./front
   volumes:
    - "./front/static:/static"
   labels:
    - "traefik.frontend.rule=Host:better-demo.com"
  api:
   build: ./api
   labels:
    - "traefik.frontend.rule=Host:better-demo.com;PathPrefix:/api"

networks:
  default:
    external:
      name: demo-network
