version: '3'

services:
  www:
   build: ./front
   labels:
    - "traefik.frontend.rule=Host:www.cubestore.com"
    - traefik.frontend.auth.basic=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/

  api:
   build: ./api
   labels:
    - "traefik.frontend.rule=Host:www.cubestore.com;PathPrefix:/api"

networks:
  default:
    external:
      name: demo-network
